services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres-db
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    volumes:
    - postgres_data:/var/lib/postgresql/data
    networks:
      postgres_network:
  redis:
    image: redis:latest  # Используем официальный образ Redis
    container_name: redis  # Имя контейнера
    ports:
      - "6379:6379"  # Проброс порта 6379 хоста на порт 6379 контейнера
    restart: unless-stopped
    volumes:
      - redis_data:/var/lib/redis/data
    networks:
      - postgres_network
networks:
  postgres_network:

volumes:
  postgres_data:
  redis_data: