spring:
    datasource:
        url: jdbc:postgresql://localhost:5423/test
        username: postgres
        password: postgres
    sql:
        init:
            mode: always
    application:
        name: MarketplaceShowcase

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                format_sql: true
    liquibase:
        change-log: classpath:/liquibase/db.changelog-master.xml
        parameters:
          app.schema-name: marketplace

logging:
    level:
        sql: debug
        org:
            springframework:
                jdbc:
                    support:
                        JdbcTransactionManager: debug
