server:
    port: 8081
spring:
    r2dbc:
        url: r2dbc:postgresql://localhost:5432/mydatabase?currentSchema=marketplace
        username: myuser
        password: secret
    datasource:
        url: jdbc:postgresql://localhost:5432/mydatabase?currentSchema=marketplace
        username: myuser
        password: secret
    sql:
        init:
            mode: always
    application:
        name: MarketplaceShowcase

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                format_sql: true
    liquibase:
        change-log: classpath:/liquibase/db.changelog-master.xml
        parameters:
          app.schema-name: marketplace
        clear-checksums: false

logging:
    level:
        sql: debug
        org:
            springframework:
                jdbc:
                    support:
                        JdbcTransactionManager: debug
