server:
    port: 8081
spring:
    r2dbc:
        url: r2dbc:postgresql://localhost:5432/mydatabase?currentSchema=marketplace
        username: myuser
        password: secret
        pool:
            enabled: true                               # Включение пула соединений
            initial-size: 10                            # Начальное количество соединений в пуле
            max-size: 50                                # Максимальное количество соединений
            max-idle-time: 30s                          # Время бездействия соединения перед закрытием
            max-life-time: 10m                          # Максимальное время жизни соединения
            validation-query: SELECT 1                  # SQL-запрос для проверки работоспособности соединения
    datasource:
        url: jdbc:postgresql://localhost:5432/mydatabase?currentSchema=marketplace
        username: myuser
        password: secret
    sql:
        init:
            mode: always
    application:
        name: MarketplaceShowcase

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                format_sql: true
    liquibase:
        change-log: classpath:/liquibase/db.changelog-master.xml
        parameters:
          app.schema-name: marketplace
        clear-checksums: false

logging:
    level:
        sql: debug
        org:
            springframework:
                jdbc:
                    support:
                        JdbcTransactionManager: debug
